server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
      force-request: true
spring:
  resources:
    static-locations: file:../front-web/main/html/
  profiles:
    include:
      # 蜂巢监控的应用配置
      - heartbeat
  datasource:
    #url: jdbc:mysql://192.168.3.19:3306/fc_gw_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullNamePatternMatchesAll=true&noAccessToProcedureBodies=true
    #username: fc_gw_test
    #password: fc_gw_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.131:3306/fc
    username: root
    password: Abc***123
    initialSize: 1
    maxActive: 5
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
#    url: jdbc:mysql://120.77.250.66:3306/fc-2.1.5
#    username: root
#    password: abc***123
#  session:
#    store-type: redis
#  redis:
#    host: 192.168.3.137
#    port: 6379
#    password: apexsoft
application:
  name: springDemo

live:
  swagger:
    enabled: true
  actuator:
    enabled: true
management:
  health:
    redis:
      enabled: false
logging:
  file:
    path: logs
